services:
  backend:
    build: .
    container_name: csv_backend
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/csvdb
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:latest
    container_name: csv_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csvdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
